photodata = {"Korea":[{"link":"http://www.polyglossiafilms.com/images/_1080484.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080483.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080477.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080476.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080472.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080458.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080445.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080430.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080431.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/_1080428.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/p1080381.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/p1080331.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/p1080329.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/p1080328.jpg",
"caption":"Another fine photo"},
{"link":"http://www.polyglossiafilms.com/images/p1080322.jpg",
"caption":"Another fine photo"}]
}
